# Generated by Django 6.0.6 on 2026-06-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='national_id',
            field=models.CharField(blank=True, help_text='Government-issued national identification number', max_length=50, unique=True),
        ),
    ]
