# Generated by Django 6.0.6 on 2026-06-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupants', '0002_student_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(blank=True, help_text='Government-issued national identification number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id_number',
            field=models.CharField(blank=True, help_text='External identifier from the educational institution', max_length=50, null=True, unique=True),
        ),
    ]
