# Generated by Django 6.0.6 on 2026-06-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['property', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
