# Generated by Django 6.0.6 on 2026-06-27 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('occupant', 'Occupant'), ('occupancy', 'Occupancy'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('property', 'Property'), ('section', 'Section'), ('unit', 'Unit'), ('pricing_rule', 'Pricing Rule'), ('user', 'User')], max_length=20)),
                ('entity_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('archive', 'Archive'), ('assign', 'Assign'), ('checkout', 'Checkout'), ('record_payment', 'Record Payment'), ('login', 'Login'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['actor'], name='audit_audit_actor_i_17b775_idx')],
            },
        ),
    ]
