# Generated by Django 6.0.6 on 2026-06-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('occupant', 'Occupant'), ('occupancy', 'Occupancy'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('property', 'Property'), ('section', 'Section'), ('unit', 'Unit'), ('pricing_rule', 'Pricing Rule'), ('user', 'User'), ('backup', 'Backup')], max_length=20),
        ),
    ]
