# Generated by Django 6.0.6 on 2026-06-26 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occupants', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null means currently active', null=True)),
                ('billing_mode', models.CharField(choices=[('semester', 'Semester'), ('monthly', 'Monthly')], default='semester', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='occupancies', to='occupants.student')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='occupancies', to='units.unit')),
            ],
            options={
                'verbose_name_plural': 'occupancies',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date'], name='occupancy_o_start_d_2c9695_idx'), models.Index(condition=models.Q(('end_date__isnull', True)), fields=['student'], name='idx_active_occupancy_per_student'), models.Index(condition=models.Q(('end_date__isnull', True)), fields=['unit'], name='idx_active_occupancy_per_unit')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='ck_occupancy_end_date_after_start')],
            },
        ),
    ]
