# Generated by Django 6.0.6 on 2026-06-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='occupancy',
            new_name='idx_occ_active_student',
            old_name='idx_active_occupancy_per_student',
        ),
        migrations.RenameIndex(
            model_name='occupancy',
            new_name='idx_occ_active_unit',
            old_name='idx_active_occupancy_per_unit',
        ),
    ]
