# Generated by Django 6.0.6 on 2026-06-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0002_rename_idx_active_occupancy_per_student_idx_occ_active_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupancy',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price snapshotted at time of assignment', max_digits=10, null=True),
        ),
    ]
