# Generated by Django 6.0.6 on 2026-06-26 12:56

import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occupants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.payments.models.validate_positive])),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('card', 'Card')], max_length=10)),
                ('reference', models.CharField(blank=True, help_text='External transaction reference', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='occupants.student')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'payment_date'], name='payments_pa_student_591a6f_idx'), models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx')],
            },
        ),
    ]
