# Generated by Django 6.0.6 on 2026-06-27 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('outstanding_balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student_name', models.CharField(max_length=300)),
                ('student_id_number', models.CharField(blank=True, max_length=50)),
                ('unit_name', models.CharField(max_length=255)),
                ('property_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=10)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='receipt', to='payments.payment')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['receipt_number'], name='payments_re_receipt_8aa2fc_idx'), models.Index(fields=['student_name'], name='payments_re_student_c7df78_idx'), models.Index(fields=['payment_date'], name='payments_re_payment_36c692_idx')],
            },
        ),
    ]
