# Generated by Django 6.0.6 on 2026-06-26 12:56

import apps.units.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.PositiveSmallIntegerField(help_text='Maximum number of occupants', validators=[apps.units.models.validate_positive])),
                ('semester_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.units.models.validate_positive])),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.units.models.validate_positive])),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='units', to='sections.section')),
            ],
            options={
                'ordering': ['section', 'name'],
                'indexes': [models.Index(fields=['capacity'], name='units_unit_capacit_46b743_idx'), models.Index(fields=['is_active'], name='units_unit_is_acti_633374_idx')],
                'constraints': [models.UniqueConstraint(fields=('section', 'name'), name='uq_unit_section_name')],
            },
        ),
    ]
