# Generated by Django 6.0.6 on 2026-06-27 20:28

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_section_options_section_order'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_mode', models.CharField(choices=[('semester', 'Semester'), ('monthly', 'Monthly')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.core.validators.validate_positive])),
                ('effective_date', models.DateField()),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['section', 'order', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='unit',
            name='units_unit_is_acti_633374_idx',
        ),
        migrations.AddField(
            model_name='unit',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status'], name='units_unit_status_08f0cf_idx'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='units.unit'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['unit', 'effective_date'], name='units_prici_unit_id_e26c68_idx'),
        ),
    ]
